[build]
  base = "src/"
  command = "npm run build"
  publish = "build"

[context.deploy-preview]
  publish = "dist/"

[[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200
    CI = false 